server:
  port: 7171

spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:scheduling_db
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
